### ISSUE TITLE
Migrate common layouts

### ISSUE THREAD

**Issue by nathanajah** [judgels-dev/raphael#5]
Based on current play-commons code:

- [x] breadcrumbsLayout
- [x] headerFooterLayout
- [ ] singleColumnLayout
- [x] twoColumnLayout
- [ ] categoryTabsLayout
- [x] contentLayout
- [ ] descriptionLayout
- [ ] mainTabsLayout
- [ ] mainTitleLayout
- [ ] secondaryTabsLayout
- [ ] flashMessagesView
- [ ] menusView

Note: We don't have to make the components exactly the same as the current judgels structure. If we want to refactor it to make it better, then we can do so.

**Comment by fushar** [comment]
Not really relevant anymore.
